# General Settings
title: "Qa'id Jacobs UX Designer and Creative Director"
email: "qaid [at] constellation.design"
email_2: 
description: >- # this means to ignore newlines until "baseurl:"
  The portfolio website of Qa'id Jacobs describes his design and leadership work in the areas of product design, team leadership, and app and website development.

black_logo_1x: "/assets/images/logo.png"
black_logo_2x: "/assets/images/logo@2x.png"
light_logo_1x: "/assets/images/logo-light.png"
light_logo_2x: "/assets/images/logo-light@2x.png"

address_01: 'Amsterdam, NL'
phone_number: ""
copyright_text: "© 2020 Qa'id Jacobs.  All rights reserved."

google_analytics:
  enable: false
  key: ""  # UA-000000000-0

social_accounts:
  title: "See me"
  links:
    - url: "https://twitter.com/qaidj"
      icon: "jam jam-twitter"

    - url: "https://instagram.com/qaid"
      icon: "jam jam-instagram"

    - url: "https://linkedin.com/in/qaidjacobs"
      icon: "jam jam-linkedin"
      
    - url: "https://github.com/qaid"
      icon: "jam jam-github"


external_links:
  title: "Learn More"
  links:
    - url: "#"
      text: "About Us"
    - url: "#"
      text: "Our Story"
    - url: "#"
      text: "Projects"
    - url: "#"
      text: "Pricing"
    - url: "#"
      text: "Features"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

footer_newsletter:
  title: ""
  sub_title: ""
  subscribe_button_text: ""


one_page_nav_settings:
  links:
    - text: "About"
      url: "#about"
    - text: "Expertise"
      url: "#expertise"
    - text: "Work"
      url: "#work"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"

gallery:
  images:
  - img: "/assets/images/client-logos/AfricanPuzzle.svg"
  - img: "/assets/images/client-logos/Booking.svg"
  - img: "/assets/images/client-logos/DesignLab.svg"
  - img: "/assets/images/client-logos/bizzylabs.svg"
  - img: "/assets/images/client-logos/channelaffairs.svg"
  - img: "/assets/images/client-logos/VONQ.svg" 